project_root: "D:/Projects/PythonProject/music-genre-classification-fma"

external_data:
  metadata_dir: "E:/music-genre-classifier/fma_metadata"
  fma_small_zip: "E:/music-genre-classifier/fma_small.zip"
  fma_medium_zip: "E:/music-genre-classifier/fma_medium.zip"
  fma_large_zip: "E:/music-genre-classifier/fma_large.zip"

  active_subset: "medium"
  active_zip: "E:/music-genre-classifier/fma_medium.zip"

project_dirs:
  data:
    raw: "./data/raw"
    processed: "./data/processed"
    external: "./data/external"
  checkpoints: "./checkpoints"
  results: "./results"
  models: "./models"
  notebooks: "./notebooks"
  logs: "./logs"
