project_root: "/home/yahor/PycharmProjects/PythonProject/music-genre-classification-fma"

external_data:
  metadata_dir: "/home/yahor/PycharmProjects/PythonProject/music-genre-classification-fma/data/raw/fma_metadata"
  fma_small_zip: "/home/yahor/PycharmProjects/PythonProject/music-genre-classification-fma/data/raw/fma_small.zip"
  fma_medium_zip: "/home/yahor/PycharmProjects/PythonProject/music-genre-classification-fma/data/raw/fma_medium.zip"
  fma_large_zip: "/home/yahor/PycharmProjects/PythonProject/music-genre-classification-fma/data/raw/fma_large.zip"

  active_subset: "medium"
  active_zip: "/home/yahor/PycharmProjects/PythonProject/music-genre-classification-fma/data/raw/fma_medium.zip"

zip_structure:
    template: "fma_{subset}/{folder}/{track_id}.mp3"
    track_id_padding: 6
    folder_chars: 3

project_dirs:
  data:
    raw: "./data/raw"
    processed: "./data/processed"
    external: "./data/external"
  checkpoints: "./checkpoints"
  results: "./results"
  models: "./models"
  notebooks: "./notebooks"
  logs: "./logs"
